### ISSUE TITLE
2.0.0 broken

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.vis-justgage#54]
2.0.0 is broken, widget files are missing

**Comment by mcm1957** [comment]
fixed with 2.0.1

**Comment by jangrik** [comment]
Sorry, nothing changed.....
the justgage widgets still dont't show up.

$ iobroker upgrade vis-justgage@2.0.1
Update vis-justgage from @2.0.0 to @2.0.1
NPM version: 9.8.1Installing iobroker.vis-justgage@2.0.1... (System call)
changed 1 package in 10s217 packages are looking for funding run `npm fund` for details
INFO: Directory "/opt/iobroker/node_modules/iobroker.vis-justgage/www" was not found! Nothing was uploaded or deleted.
Adapter "system.adapter.vis.0" restarted.
Update "system.adapter.vis-justgage.0"
upload [2] vis-justgage.admin /opt/iobroker/node_modules/iobroker.vis-justgage/admin/index.html index.html text/html
upload [1] vis-justgage.admin /opt/iobroker/node_modules/iobroker.vis-justgage/admin/index_m.html index_m.html text/html
upload [0] vis-justgage.admin /opt/iobroker/node_modules/iobroker.vis-justgage/admin/justgage.png justgage.png image/png
Process exited with code 0

**Comment by Apollon77** [comment]
please restart vis

**Comment by jangrik** [comment]
I restarted vis and even restartet iobroker and the os. And cleared the browser cache and tried a different browser (edge).

**Comment by mcm1957** [comment]
Thanks for feedback and sorry for malfunction
Just for completeness please add rest of version infos:

vis
js-controller
node

I'ff investigate futher

**Comment by mcm1957** [comment]
@jangrik 
Please retest with 2.0.2 (available ab github and npm now, at latest repo tomorrow.

I detected another chnage occured during migration which seems to be suspect and has been reverted.

**Comment by Pocky2507** [comment]
Version 2.0.2

`INFO: Directory "/opt/iobroker/node_modules/iobroker.vis-justgage/www" was not found! Nothing was uploaded or deleted.
Adapter "system.adapter.vis.0" restarted.
Update "system.adapter.vis-justgage.0"
upload [2] vis-justgage.admin /opt/iobroker/node_modules/iobroker.vis-justgage/admin/index.html index.html text/html
upload [1] vis-justgage.admin /opt/iobroker/node_modules/iobroker.vis-justgage/admin/index_m.html index_m.html text/html
upload [0] vis-justgage.admin /opt/iobroker/node_modules/iobroker.vis-justgage/admin/justgage.png justgage.png image/png
`

**Comment by mcm1957** [comment]
@Pocky2507 
not sure what you wanted to tell.
The INFO line is normal and OK as this adapter does not provide files at www directory.

**Comment by jangrik** [comment]
sorry, same with version 2.0.2.
vis 1.5.1
node.js 18.18.2
js-controller 5.0.16

**Comment by mcm1957** [comment]
Did you install from npm or directls from github?
If installed from github please check that an instance exists (and eventually delete and recreate the instance.
And do a manual upload

**Comment by jangrik** [comment]
success!!! you did it, thanks a lot!!!!!!!!!!!!
I deleteted the adapter v 2.0.2 and immediatly reinstalled it, and voila, now the widgets are there.
Thanks!
